# Generated by Django 4.2.2 on 2023-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='audio_file',
            field=models.FileField(upload_to='audio/wav'),
        ),
    ]
