# Generated by Django 4.2.2 on 2023-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fft_features',
            field=models.BinaryField(),
        ),
    ]
