# Generated by Django 4.2.2 on 2023-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fft_features',
            field=models.TextField(),
        ),
    ]
