# Generated by Django 4.2.2 on 2023-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='email',
            field=models.EmailField(default='fake@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='login_audio/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='fft_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='audio_file',
            field=models.FileField(upload_to='register_audio/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='fake@gmail.com', max_length=100),
        ),
    ]
