# Generated by Django 4.2.2 on 2023-06-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_audiofile_email_alter_audiofile_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
